<?php

$banks_list = [
    // --- NORTH AMERICA (USA & CANADA) - Approx. 70 Banks ---
    "Bank of America",
    "JPMorgan Chase",
    "Wells Fargo",
    "Citibank",
    "U.S. Bank",
    "PNC Bank",
    "Truist Financial",
    "Goldman Sachs",
    "Morgan Stanley",
    "Capital One",
    "TD Bank, N.A. (US)",
    "BMO Harris Bank (US)",
    "Regions Bank",
    "Ally Bank",
    "KeyBank",
    "Fifth Third Bank",
    "M&T Bank",
    "State Street Corporation",
    "Bank of New York Mellon",
    "Northern Trust",
    "Huntington National Bank",
    "Comerica Bank",
    "Zions Bancorporation",
    "Synchrony Bank",
    "Discover Bank",
    "Charles Schwab Bank",
    "Silicon Valley Bank (SVB)",
    "First Republic Bank (now JPMorgan Chase)",
    "Citizens Financial Group",
    "Wintrust Financial",
    "Royal Bank of Canada (RBC)",
    "Toronto-Dominion Bank (TD)",
    "Bank of Nova Scotia (Scotiabank)",
    "Bank of Montreal (BMO)",
    "Canadian Imperial Bank of Commerce (CIBC)",
    "National Bank of Canada",
    "Laurentian Bank of Canada",
    "HSBC Bank Canada",
    "Desjardins Group",
    "Equitable Bank",
    "Manulife Bank of Canada",
    "Simplii Financial",
    "Tangerine Bank",
    "ATB Financial",
    "Credit Suisse ( UBS)",
    "UBS Group AG (US/Canada)",
    "Sumitomo Mitsui Banking Corporation (US)",
    "MUFG Bank (US)",
    "Industrial and Commercial Bank of China (US)",
    "China Construction Bank (US)",
    "Mizuho Bank (US)",
    "Deutsche Bank (US)",
    "BNP Paribas (US)",
    "Société Générale (US)",
    "Santander Bank, N.A. (US)",
    "Standard Chartered (US)",
    "BancorpSouth Bank",
    "Fulton Bank",
    "Cathay Bank",
    "East West Bank",
    "People's United Bank (now M&T Bank)",
    "Webster Bank",
    "City National Bank",
    "TCF Financial Corporation (Huntington)",
    "First Horizon Bank",
    "Frost Bank",
    "Texas Capital Bank",
    "Sterling Bank and Trust",

    // --- EUROPE - Approx. 140 Banks ---
    "HSBC",
    "Barclays",
    "Lloyds Bank",
    "NatWest Group (includes NatWest, Royal Bank of Scotland, Ulster Bank)",
    "Standard Chartered",
    "Santander UK",
    "Virgin Money UK",
    "Coutts & Co",
    "Co-operative Bank (UK)",
    "TSB Bank (UK)",
    "Metro Bank (UK)",
    "Monzo Bank (UK)",
    "Revolut (Lithuania/UK)",
    "Deutsche Bank",
    "Commerzbank",
    "DZ Bank",
    "Bayerische Landesbank (BayernLB)",
    "Landesbank Baden-Württemberg (LBBW)",
    "KfW Bankengruppe",
    "Postbank (Germany)",
    "ING Group",
    "ABN AMRO",
    "Rabobank",
    "BNP Paribas",
    "Société Générale",
    "Crédit Agricole",
    "Crédit Mutuel",
    "Groupe BPCE (Banques Populaires/Caisses d'Epargne)",
    "La Banque Postale",
    "Intesa Sanpaolo",
    "UniCredit",
    "Banca Monte dei Paschi di Siena",
    "Banco BPM",
    "UBI Banca (now Intesa Sanpaolo)",
    "CaixaBank",
    "BBVA",
    "Banco Sabadell",
    "Bankia (now CaixaBank)",
    "Bankinter",
    "Unicaja Banco",
    "Novo Banco (Portugal)",
    "Banco Comercial Português (BCP Millennium)",
    "DNB ASA (Norway)",
    "Nordea (Finland/Sweden)",
    "Handelsbanken (Sweden)",
    "SEB (Sweden)",
    "Swedbank (Sweden)",
    "Danske Bank (Denmark)",
    "Powszechna Kasa Oszczędności Bank Polski (PKO BP)",
    "Bank Pekao (Poland)",
    "Bank Millennium (Poland)",
    "Erste Group Bank (Austria)",
    "Raiffeisen Bank International (Austria)",
    "VTB Bank (Russia)",
    "Sberbank (Russia)",
    "Gazprombank (Russia)",
    "Alfa-Bank (Russia)",
    "Bank of Cyprus",
    "Hellenic Bank (Cyprus)",
    "Piraeus Bank (Greece)",
    "National Bank of Greece",
    "Eurobank Ergasias (Greece)",
    "Alpha Bank (Greece)",
    "KBC Group (Belgium)",
    "Belfius (Belgium)",
    "Standard Bank of South Africa (London)",
    "Garanti BBVA (Turkey)",
    "Akbank (Turkey)",
    "Türkiye İş Bankası (Turkey)",
    "Ziraat Bankası (Turkey)",
    "UniCredit Bank Austria",
    "Bank Zachodni WBK (now Santander Bank Polska)",
    "Sparebank 1 SR-Bank (Norway)",
    "Jyske Bank (Denmark)",
    "Bank of Ireland",
    "Allied Irish Banks (AIB)",
    "Ulster Bank Ireland (RBS Group)",
    "Permanent TSB (Ireland)",
    "RBC Investor & Treasury Services (Luxembourg)",
    "J. Safra Sarasin (Switzerland)",
    "Julius Baer (Switzerland)",
    "Pictet Group (Switzerland)",
    "Lombard Odier (Switzerland)",
    "EFG International (Switzerland)",
    "DekaBank (Germany)",
    "Helaba (Germany)",
    "VP Bank (Liechtenstein)",
    "LGT Bank (Liechtenstein)",
    "Raiffeisen Schweiz (Switzerland)",
    "Bank Vontobel (Switzerland)",
    "HypoVereinsbank (Germany)",
    "Caixa Geral de Depósitos (CGD) (Portugal)",
    "Bank of Valletta (Malta)",
    "Central Bank of Malta (BOM)",
    "Nordeus Bank (Serbia)",
    "OTP Bank (Hungary)",
    "Česká spořitelna (Czechia)",
    "Komerční banka (Czechia)",
    "Tatra banka (Slovakia)",
    "Slovenska sporitelna (Slovakia)",
    "Privredna banka Zagreb (Croatia)",
    "UniCredit Bank Slovenia",
    "Raffeisen Bank Albania",
    "NLB d.d. (Slovenia)",
    "UniCredit Bank Serbia",
    "Piraeus Bank Romania",
    "CEC Bank (Romania)",
    "Banca Transilvania (Romania)",
    "Bank Leumi (Israel)",
    "Bank Hapoalim (Israel)",
    "Mizrahi-Tefahot Bank (Israel)",

    // --- ASIA PACIFIC - Approx. 190 Banks ---
    "Industrial and Commercial Bank of China (ICBC)",
    "China Construction Bank (CCB)",
    "Agricultural Bank of China (ABC)",
    "Bank of China (BOC)",
    "Bank of Communications (BoCom)",
    "Postal Savings Bank of China (PSBC)",
    "China Merchants Bank",
    "Industrial Bank (China)",
    "China Minsheng Banking Corp",
    "Shanghai Pudong Development Bank (SPDB)",
    "CITIC Bank",
    "Ping An Bank",
    "Evergrowing Bank",
    "Huaxia Bank",
    "Hangzhou Bank",
    "Bank of Beijing",
    "Bank of Shanghai",
    "Sumitomo Mitsui Financial Group (SMFG)",
    "Mitsubishi UFJ Financial Group (MUFG)",
    "Mizuho Financial Group",
    "Japan Post Bank",
    "Norinchukin Bank",
    "Resona Holdings",
    "Shinsei Bank",
    "Aozora Bank",
    "Bank of Yokohama",
    "Shizuoka Bank",
    "Fukuoka Financial Group",
    "HSBC Hong Kong",
    "Standard Chartered Hong Kong",
    "Bank of East Asia (BEA)",
    "Hang Seng Bank (Hong Kong)",
    "DBS Bank (Singapore)",
    "Oversea-Chinese Banking Corp (OCBC)",
    "United Overseas Bank (UOB)",
    "Maybank (Malaysia)",
    "CIMB Group (Malaysia)",
    "Public Bank Berhad (Malaysia)",
    "RHB Bank (Malaysia)",
    "AmBank Group (Malaysia)",
    "Bank Rakyat Indonesia (BRI)",
    "Bank Mandiri (Indonesia)",
    "Bank Central Asia (BCA)",
    "Bank Negara Indonesia (BNI)",
    "BDO Unibank (Philippines)",
    "Metropolitan Bank and Trust Company (Metrobank) (Philippines)",
    "Bank of the Philippine Islands (BPI)",
    "Philippine National Bank (PNB)",
    "Commonwealth Bank of Australia (CBA)",
    "Westpac Banking Corporation",
    "ANZ Banking Group",
    "National Australia Bank (NAB)",
    "Macquarie Group (Australia)",
    "Bendigo and Adelaide Bank (Australia)",
    "Bank of Queensland",
    "KiwiBank (New Zealand)",
    "ASB Bank (New Zealand)",
    "Westpac New Zealand",
    "Bank of India",
    "State Bank of India (SBI)",
    "HDFC Bank (India)",
    "ICICI Bank (India)",
    "Axis Bank (India)",
    "Punjab National Bank (PNB) (India)",
    "Canara Bank (India)",
    "Bank of Baroda (India)",
    "Union Bank of India",
    "Kotak Mahindra Bank (India)",
    "IndusInd Bank (India)",
    "Yes Bank (India)",
    "IDFC First Bank (India)",
    "Shinhan Financial Group (South Korea)",
    "KB Financial Group (South Korea)",
    "Hana Financial Group (South Korea)",
    "Woori Financial Group (South Korea)",
    "Industrial Bank of Korea (IBK)",
    "Nonghyup Bank (NH Bank) (South Korea)",
    "KEB Hana Bank (South Korea)",
    "Agricultural Bank of Korea (NongHyup)",
    "Kasikornbank (Thailand)",
    "Bangkok Bank (Thailand)",
    "Siam Commercial Bank (SCB) (Thailand)",
    "Krungthai Bank (Thailand)",
    "Vietcombank (Vietnam)",
    "VietinBank (Vietnam)",
    "BIDV (Vietnam)",
    "Agribank (Vietnam)",
    "Commercial Bank of Ceylon (Sri Lanka)",
    "Hatton National Bank (HNB) (Sri Lanka)",
    "DFCC Bank (Sri Lanka)",
    "Bank of Ceylon (Sri Lanka)",
    "Janata Bank (Bangladesh)",
    "Sonali Bank (Bangladesh)",
    "Islami Bank Bangladesh",
    "The City Bank (Bangladesh)",
    "MCB Bank (Pakistan)",
    "Habib Bank Limited (HBL) (Pakistan)",
    "United Bank Limited (UBL) (Pakistan)",
    "Allied Bank Limited (ABL) (Pakistan)",
    "Faysal Bank (Pakistan)",
    "Bank Muscat (Oman)",
    "National Bank of Oman",
    "Qatar National Bank (QNB)",
    "First Abu Dhabi Bank (FAB)",
    "Emirates NBD (Dubai)",
    "Abu Dhabi Commercial Bank (ADCB)",
    "Dubai Islamic Bank (DIB)",
    "Kuwait Finance House (KFH)",
    "National Bank of Kuwait (NBK)",
    "Samba Financial Group (Saudi Arabia)",
    "Al Rajhi Bank (Saudi Arabia)",
    "Riyad Bank (Saudi Arabia)",
    "Saudi British Bank (SABB)",
    "Bank AlJazira (Saudi Arabia)",
    "Gulf Bank (Kuwait)",
    "Ahli United Bank (Bahrain)",
    "Bank of Bahrain and Kuwait (BBK)",
    "Jordan Ahli Bank",
    "Arab Bank (Jordan)",
    "Commercial Bank of Qatar",
    "Mashreq Bank (UAE)",
    "Sharjah Islamic Bank (UAE)",
    "Bank Sohar (Oman)",
    "Bank Dhofar (Oman)",
    "Nepal Investment Bank",
    "Standard Chartered Bank Nepal",
    "Bank of Bhutan",
    "T Bank (Bhutan)",
    "Bank of Maldives",
    "State Bank of Pakistan",
    "Bank of Ceylon (India)",
    "Bank of China (Overseas Branches)",
    "Bank of America (Asia Pacific)",
    "JPMorgan Chase (Asia Pacific)",
    "Wells Fargo (Asia Pacific)",
    "Citibank (Asia Pacific)",
    "U.S. Bank (Asia Pacific)",
    "PNC Bank (Asia Pacific)",
    "Truist Financial (Asia Pacific)",
    "HSBC (Asia Pacific)",
    "Barclays (Asia Pacific)",
    "Lloyds Bank (Asia Pacific)",
    "Deutsche Bank (Asia Pacific)",
    "BNP Paribas (Asia Pacific)",
    "Société Générale (Asia Pacific)",
    "Crédit Agricole (Asia Pacific)",
    "Santander (Asia Pacific)",
    "BBVA (Asia Pacific)",
    "CaixaBank (Asia Pacific)",
    "Intesa Sanpaolo (Asia Pacific)",
    "UniCredit (Asia Pacific)",
    "ING Group (Asia Pacific)",
    "Rabobank (Asia Pacific)",
    "ABN AMRO (Asia Pacific)",
    "Scotiabank (Asia Pacific)",
    "Royal Bank of Canada (Asia Pacific)",
    "Toronto-Dominion Bank (Asia Pacific)",
    "Bank of Montreal (Asia Pacific)",
    "CIBC (Asia Pacific)",
    "National Australia Bank (Asia Pacific)",
    "Commonwealth Bank (Asia Pacific)",
    "ANZ Bank (Asia Pacific)",
    "Westpac (Asia Pacific)",
    "Standard Bank (Asia Pacific)",
    "FirstRand Bank (Asia Pacific)",

    // --- LATIN AMERICA - Approx. 50 Banks ---
    "Itau Unibanco (Brazil)",
    "Banco do Brasil",
    "Bradesco (Brazil)",
    "Caixa Econômica Federal (Brazil)",
    "Santander Brasil",
    "Banco Safra (Brazil)",
    "BTG Pactual (Brazil)",
    "Banco Original (Brazil)",
    "Banco de Crédito e Inversiones (BCI) (Chile)",
    "Banco Santander Chile",
    "Banco de Chile",
    "Banco del Estado de Chile (BancoEstado)",
    "BBVA Bancomer (Mexico - now BBVA México)",
    "Citibanamex (Mexico)",
    "Santander México",
    "Banorte (Mexico)",
    "HSBC México",
    "Scotiabank Inverlat (Mexico)",
    "Banco de Bogotá (Colombia)",
    "Bancolombia",
    "Davivienda (Colombia)",
    "BBVA Colombia",
    "Banco Pichincha (Ecuador)",
    "Produbanco (Ecuador)",
    "Banco de Crédito del Perú (BCP)",
    "Interbank (Peru)",
    "Scotiabank Perú",
    "Banco Continental (BBVA Perú)",
    "Banco Mercantil (Venezuela)",
    "Banco Provincial (Venezuela)",
    "Banco de Venezuela",
    "Banco Galicia (Argentina)",
    "Banco Macro (Argentina)",
    "Banco Santander Río (Argentina)",
    "BBVA Argentina",
    "Banco Central de la República Argentina (BCRA)",
    "Banco Itaú (Argentina)",
    "Banco Hipotecario (Argentina)",
    "Banco G&T Continental (Guatemala)",
    "Banco Industrial (Guatemala)",
    "Banco Azteca (Mexico/Central America)",
    "Banco Ficohsa (Honduras/Central America)",
    "BAC Credomatic (Central America)",
    "Banco General (Panama)",
    "Banistmo (Panama)",
    "Banco Popular Dominicano (Dominican Republic)",
    "Banco Caribe (Dominican Republic)",
    "Banco de Reservas de la República Dominicana",
    "First Caribbean International Bank (CIBC FirstCaribbean)",

    // --- AFRICA & MIDDLE EAST (Non-Asian ME) - Approx. 50 Banks ---
    "Standard Bank (South Africa)",
    "FirstRand Bank (FNB) (South Africa)",
    "Absa Group (South Africa)",
    "Nedbank (South Africa)",
    "Capitec Bank (South Africa)",
    "Investec (South Africa/UK)",
    "Zenith Bank (Nigeria)",
    "Guaranty Trust Bank (GTBank) (Nigeria)",
    "Access Bank (Nigeria)",
    "United Bank for Africa (UBA) (Nigeria)",
    "Ecobank Transnational Incorporated (ETI) (Togo/Pan-African)",
    "Equity Bank (Kenya)",
    "KCB Bank (Kenya)",
    "Co-operative Bank of Kenya",
    "Standard Chartered Kenya",
    "Commercial International Bank (CIB) (Egypt)",
    "National Bank of Egypt",
    "Banque Misr (Egypt)",
    "Attijariwafa Bank (Morocco)",
    "Banque Centrale Populaire (BCP) (Morocco)",
    "BMCE Bank (Morocco)",
    "Al Baraka Banking Group (Bahrain/Global Islamic)",
    "Arab Banking Corporation (ABC) (Bahrain)",
    "Al Ahli Bank of Kuwait (ABK)",
    "Commercial Bank of Kuwait (CBK)",
    "Burgan Bank (Kuwait)",
    "Housing Bank for Trade and Finance (Jordan)",
    "Cairo Amman Bank (Jordan)",
    "Bank Audi (Lebanon)",
    "Fransabank (Lebanon)",
    "Blom Bank (Lebanon)",
    "Bank Al-Maghrib (Morocco)",
    "National Commercial Bank (NCB) (Saudi Arabia - now Saudi National Bank)",
    "Alinma Bank (Saudi Arabia)",
    "Bank of Khartoum (Sudan)",
    "Bank of Africa (BOA) (Benin/Pan-African)",
    "Ghana Commercial Bank (GCB)",
    "Fidelity Bank Ghana",
    "Société Générale Ghana",
    "Zambia National Commercial Bank (ZANACO)",
    "NMB Bank (Tanzania)",
    "CRDB Bank (Tanzania)",
    "Caledonian Bank (Cayman Islands)",
    "Butterfield Bank (Bermuda)",
    "Sagicor Bank Jamaica",
    "First Citizens Bank (Trinidad and Tobago)",
    "Republic Bank Limited (Trinidad and Tobago/Caribbean)",
    "Eastern Caribbean Central Bank (ECCB)",
];

// Convert to JSON for JavaScript use
$banks_json = json_encode($banks_list);
